---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: atomic-desktop
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      - brave-browser
      - micro
      - starship
      - zsh

  - type: bling
    install:
      - 1password

  - type: brew
    nofile-limits: true

  - type: fonts
    fonts:
      nerd-fonts:
        - Meslo
        - JetBrainsMono

  - type: default-flatpaks
    notify: true 
    system:
      install:
        - org.gnome.Loupe
        - com.discordapp.Discord
        - com.valvesoftware.Steam
      remove:
        - org.gnome.eog
    user: {} 

  - type: systemd
    user:
      enabled:
        - 1password.service

  - type: yafti

  - type: signing 

